# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/gohugoio/localescompressed
%global goipath         github.com/gohugoio/localescompressed
Version:                0.14.0

%gometa

%global common_description %{expand:
The locales from https://github.com/gohugoio/locales in one package/struct.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        The locales from https://github.com/gohugoio/locales in one package/struct

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-playground/locales)
BuildRequires:  golang(github.com/go-playground/locales/currency)
BuildRequires:  golang(golang.org/x/tools/go/packages)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/bep/workers)
BuildRequires:  golang(github.com/frankban/quicktest)
BuildRequires:  golang(github.com/go-playground/locales/en)
BuildRequires:  golang(github.com/go-playground/locales/nn)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

sed -i \
    -e 's|"github.com/gohugoio/locales|"github.com/go-playground/locales|' \
    $(find . -name '*.go')

%build
for cmd in gen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Aug 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.14.0-1%{?dist}
- Initial package

