# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/gohugoio/hugo
%global goipath         github.com/gohugoio/hugo
Version:                0.86.0

%gometa

%global common_description %{expand:
The world’s fastest framework for building websites.}

%global golicenses      LICENSE docs/LICENSE.md\\\
                        docs/content/en/about/license.md
%global godocs          examples docs CONTRIBUTING.md SECURITY.md README.md\\\
                        tpl/tplimpl/embedded/README.md\\\
                        tpl/tplimpl/embedded/templates/_default/robots.txt\\\
                        hugolib/testsite/content_nn/first-post.md\\\
                        hugolib/testsite/content/first-post.md\\\
                        temp/0.86.0-relnotes-ready.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        The world’s fastest framework for building websites

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/alecthomas/chroma)
BuildRequires:  golang(github.com/alecthomas/chroma/formatters/html)
BuildRequires:  golang(github.com/alecthomas/chroma/lexers)
BuildRequires:  golang(github.com/alecthomas/chroma/styles)
BuildRequires:  golang(github.com/armon/go-radix)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/cloudfront)
BuildRequires:  golang(github.com/bep/debounce)
BuildRequires:  golang(github.com/bep/gitmap)
BuildRequires:  golang(github.com/bep/godartsass)
BuildRequires:  golang(github.com/bep/gowebp/libwebp/webpoptions)
BuildRequires:  golang(github.com/bep/tmc)
BuildRequires:  golang(github.com/BurntSushi/locker)
BuildRequires:  golang(github.com/BurntSushi/toml)
BuildRequires:  golang(github.com/cli/safeexec)
BuildRequires:  golang(github.com/disintegration/gift)
BuildRequires:  golang(github.com/dustin/go-humanize)
BuildRequires:  golang(github.com/evanw/esbuild/pkg/api)
BuildRequires:  golang(github.com/frankban/quicktest)
BuildRequires:  golang(github.com/fsnotify/fsnotify)
BuildRequires:  golang(github.com/getkin/kin-openapi/openapi3)
BuildRequires:  golang(github.com/ghodss/yaml)
BuildRequires:  golang(github.com/gobuffalo/flect)
BuildRequires:  golang(github.com/gobwas/glob)
BuildRequires:  golang(github.com/gobwas/glob/syntax)
BuildRequires:  golang(github.com/gohugoio/go-i18n/v2/i18n)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/gorilla/websocket)
BuildRequires:  golang(github.com/jdkato/prose/transform)
BuildRequires:  golang(github.com/kyokomi/emoji/v2)
BuildRequires:  golang(github.com/mattn/go-isatty)
BuildRequires:  golang(github.com/miekg/mmark)
BuildRequires:  golang(github.com/mitchellh/hashstructure)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/muesli/smartcrop)
BuildRequires:  golang(github.com/niklasfasching/go-org/org)
BuildRequires:  golang(github.com/olekukonko/tablewriter)
BuildRequires:  golang(github.com/pelletier/go-toml)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/PuerkitoBio/purell)
BuildRequires:  golang(github.com/rogpeppe/go-internal/module)
BuildRequires:  golang(github.com/russross/blackfriday)
BuildRequires:  golang(github.com/rwcarlsen/goexif/exif)
BuildRequires:  golang(github.com/rwcarlsen/goexif/tiff)
BuildRequires:  golang(github.com/sanity-io/litter)
BuildRequires:  golang(github.com/spf13/afero)
BuildRequires:  golang(github.com/spf13/cast)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/cobra/doc)
BuildRequires:  golang(github.com/spf13/fsync)
BuildRequires:  golang(github.com/spf13/jwalterweatherman)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(github.com/tdewolff/minify/v2)
BuildRequires:  golang(github.com/tdewolff/minify/v2/css)
BuildRequires:  golang(github.com/tdewolff/minify/v2/html)
BuildRequires:  golang(github.com/tdewolff/minify/v2/js)
BuildRequires:  golang(github.com/tdewolff/minify/v2/json)
BuildRequires:  golang(github.com/tdewolff/minify/v2/svg)
BuildRequires:  golang(github.com/tdewolff/minify/v2/xml)
BuildRequires:  golang(github.com/yuin/goldmark)
BuildRequires:  golang(github.com/yuin/goldmark-highlighting)
BuildRequires:  golang(github.com/yuin/goldmark/ast)
BuildRequires:  golang(github.com/yuin/goldmark/extension)
BuildRequires:  golang(github.com/yuin/goldmark/parser)
BuildRequires:  golang(github.com/yuin/goldmark/renderer)
BuildRequires:  golang(github.com/yuin/goldmark/renderer/html)
BuildRequires:  golang(github.com/yuin/goldmark/text)
BuildRequires:  golang(github.com/yuin/goldmark/util)
BuildRequires:  golang(gocloud.dev/blob)
BuildRequires:  golang(gocloud.dev/blob/azureblob)
BuildRequires:  golang(gocloud.dev/blob/fileblob)
BuildRequires:  golang(gocloud.dev/blob/gcsblob)
BuildRequires:  golang(gocloud.dev/blob/s3blob)
BuildRequires:  golang(gocloud.dev/gcerrors)
BuildRequires:  golang(golang.org/x/image/bmp)
BuildRequires:  golang(golang.org/x/image/tiff)
BuildRequires:  golang(golang.org/x/image/webp)
BuildRequires:  golang(golang.org/x/net/html)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/sync/semaphore)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(golang.org/x/text/runes)
BuildRequires:  golang(golang.org/x/text/transform)
BuildRequires:  golang(golang.org/x/text/unicode/norm)
BuildRequires:  golang(google.golang.org/api/compute/v1)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/fortytw2/leaktest)
BuildRequires:  golang(github.com/gohugoio/testmodBuilder/mods)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(github.com/kylelemons/godebug/diff)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(gocloud.dev/blob/memblob)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/hugo %{goipath}
for cmd in scripts/fork_go_templates tpl/tplimpl/embedded/generate; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE docs/LICENSE.md docs/content/en/about/license.md
%doc examples docs CONTRIBUTING.md SECURITY.md README.md
%doc tpl/tplimpl/embedded/README.md
%doc tpl/tplimpl/embedded/templates/_default/robots.txt
%doc hugolib/testsite/content_nn/first-post.md
%doc hugolib/testsite/content/first-post.md temp/0.86.0-relnotes-ready.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Aug 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.86.0-1%{?dist}
- Initial package

