# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/nicksnyder/go-i18n
%global goipath         github.com/nicksnyder/go-i18n
Version:                2.1.2

%gometa

%global common_description %{expand:
Translate your Go program into multiple languages.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md example

Name:           %{goname}
Release:        1%{?dist}
Summary:        Translate your Go program into multiple languages

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

Patch0001:      dadad2bdb2a713748df0717eddd54495150cfb58.patch

BuildRequires:  golang(github.com/BurntSushi/toml)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(gopkg.in/yaml.v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%patch0001 -p1

%build
for cmd in v2/goi18n; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Aug 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 2.1.2-1%{?dist}
- Initial package

