# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/bep/workers
%global goipath         github.com/bep/workers
Version:                1.0.0

%gometa

%global common_description %{expand:
Set up tasks to be executed in parallel.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Set up tasks to be executed in parallel

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sync/errgroup)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/frankban/quicktest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.0.0-1%{?dist}
- Initial package

