# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/bep/gowebp
%global goipath         github.com/bep/gowebp
Version:                0.1.0

%gometa

%global common_description %{expand:
C bindings and an API for encoding Webp images.}

%global golicenses      LICENSE libwebp_src/PATENTS libwebp_src/COPYING
%global godocs          README.md libwebp_src/README\\\
                        libwebp_src/AUTHORS libwebp_src/README.webp_js\\\
                        libwebp_src/README.mux libwebp_src/ChangeLog\\\
                        libwebp_src/swig/README

Name:           %{goname}
Release:        1%{?dist}
Summary:        C bindings and an API for encoding Webp images

# Upstream license specification: BSD-3-Clause and MIT
License:        BSD and MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(golang.org/x/image/webp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in gen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE libwebp_src/PATENTS libwebp_src/COPYING
%doc README.md libwebp_src/README libwebp_src/AUTHORS
%doc libwebp_src/README.webp_js libwebp_src/README.mux libwebp_src/ChangeLog
%doc libwebp_src/swig/README
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Aug 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.1.0-1%{?dist}
- Initial package

