# Generated by go2rpm 1
%bcond_without check

# https://github.com/go-playground/locales
%global goipath         github.com/go-playground/locales
Version:                0.14.0

%gometa

%global common_description %{expand:
A set of locales generated from the CLDR Project which can be
used independently or within an i18n package; these were built for use with,
but not exclusive to https://github.com/go-playground/universal-translator.}

%global golicenses      LICENSE
%global godocs          README.md cmd/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A set of locales generated from the CLDR Project

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/text/unicode/cldr)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.13.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.13.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jul 26 18:52:46 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.13.0-1
- Initial package
