# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/gohugoio/locales
%global goipath         github.com/gohugoio/locales
Version:                0.14.0

%gometa

%global common_description %{expand:
:earth_americas: a set of locales generated from the CLDR Project which can be
used independently or within an i18n package; these were built for use with,
but not exclusive to https://github.com/go-playground/universal-translator.}

%global golicenses      LICENSE
%global godocs          README.md cmd/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        :earth_americas: a set of locales generated from the CLDR Project which can be used independently or within an i18n package; these were built for use with, but not exclusive to https://github.com/go-playground/universal-translator

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/text/unicode/cldr)

%description
%{common_description}

%gopkg

%prep
%goprep

rm eu/ue_test.go


%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 22 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.14.0-1%{?dist}
- Initial package

